name: web_to_markdown
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - beautifulsoup4==4.12.2
    - requests==2.31.0
    - openai>=1.57.4
    - python-dotenv==1.0.0
    - markdown==3.5.1
    - "flask[async]==3.0.0"
    - flask-wtf==1.2.1
    - asgiref==3.7.2
